version: "1.0"
info:
  model: int-scaffold
packages:
- name: BE_PR_DEMO_GITProject
  gitServerName: be_pr_wm_git
  gitUrl: https://github.com/prichelle
  gitUsername: prichelle
  gitBranch: main
- name: wmAppIntegration
  version: "1.0"
  gitServerName: be_pr_wm_git
  gitUrl: https://github.com/prichelle
  gitUsername: prichelle
  gitBranch: main
- name: OrderEntry
  version: 2.3.0
  gitServerName: be_pr_wm_git
  gitUrl: https://github.com/prichelle
  gitUsername: prichelle
  gitBranch: master
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.be_pr_demo_git.integrations:getOrderDB
  packages:
  - name: BE_PR_DEMO_GITProject
    version: "1.0"
  - name: wmAppIntegration
    version: "1.0"
  - name: OrderEntry
    version: 2.3.0
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.be_pr_demo_git.integrations:logdebug
  packages:
  - name: BE_PR_DEMO_GITProject
    version: "1.0"
  - name: wmAppIntegration
    version: "1.0"
  - name: OrderEntry
    version: 2.3.0
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: WmAppIntegration.services:createSalesOrder
  packages:
  - name: wmAppIntegration
    version: "1.0"
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.json:jsonStreamToDocument
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: project.be_pr_demo_git.integrations:testOrderEntry
  packages:
  - name: BE_PR_DEMO_GITProject
    version: "1.0"
  - name: wmAppIntegration
    version: "1.0"
  - name: OrderEntry
    version: 2.3.0
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: orderentry.adapter:getOrderLineItems
  packages:
  - name: OrderEntry
    version: 2.3.0
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.databaseName
  : ordermgt
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionManagerSettings.poolable
  : "false"
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.user
  : root
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.driverType
  : mysql
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.trustStore
  : ""
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.password
  : "{AES}R8T5JD08oJzYmvTAa6hLaA=="
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.serverName
  : mysqldb
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.dbType
  : MySQL
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.portNumber
  : "3306"
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.keyStore
  : ""
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.networkProtocol
  : ""
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.BE_PR_DEMO_GITProject.project.be_pr_demo_git.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mySQL_local_mac.connectionEnabled
  : "false"
